### ISSUE TITLE
Boto exception when running example code

### ISSUE THREAD

**Issue by StefanB7** [labrixdigital/cloudwatch#13]
Hi.
I'm having some trouble using this library. I wrote a simple python program to test logging to cloudflare logs, that is basically the same as the example in the readme:

```python
import os
import logging
from cloudwatch import cloudwatch
from dotenv import load_dotenv

load_dotenv()

AWS_KEY = os.getenv("AWS_KEY")
AWS_SECRET_KEY = os.getenv("AWS_SECRET_KEY")

logger = logging.getLogger("my_logger")
formatter = logging.Formatter('%(asctime)s : %(levelname)s - %(message)s')
cloudwatch_handler = cloudwatch.CloudwatchHandler(
    log_group="log_group_example", log_stream="log_stream_example",
    access_id=AWS_KEY, access_key=AWS_SECRET_KEY,
    region="af-south-1")
cloudwatch_handler.setFormatter(formatter)
logger.setLevel(logging.INFO)
logger.addHandler(cloudwatch_handler)

logger.warning("Testing 1 2 3 . . .")
```

When running the program, the log group and log stream is created on Cloudwatch, but I get the following exception:
```
Traceback (most recent call last):
  File "c:\Users\User\Documents\Repos\Orchestrator\temp.py", line 21, in <module>
    logger.warning("Testing 1 2 3 . . .")
  File "C:\Program Files\Python311\Lib\logging\__init__.py", line 1501, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "C:\Program Files\Python311\Lib\logging\__init__.py", line 1634, in _log
    self.handle(record)
  File "C:\Program Files\Python311\Lib\logging\__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "C:\Program Files\Python311\Lib\logging\__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "C:\Program Files\Python311\Lib\logging\__init__.py", line 978, in handle
    self.emit(record)
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\cloudwatch\cloudwatch.py", line 103, in emit
    self._send(log_entry)
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\cloudwatch\cloudwatch.py", line 125, in _send
    self.send_log(timestamp, log_entry)
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\cloudwatch\cloudwatch.py", line 88, in send_log
    self.logs.put_log_events(logGroupName=self.log_group,
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\botocore\client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\botocore\client.py", line 936, in _make_api_call
    request_dict = self._convert_to_request_dict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\botocore\client.py", line 1007, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\botocore\validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter sequenceToken, value: 0, valid min length: 1
```

It seems like the error is coming from the `send_log` function inside `cloudwatch.py`.
```python
def send_log(self, timestamp, log_entry):
  #Send the message to AWS
  self.logs.put_log_events(logGroupName=self.log_group,
      logStreamName=self.log_stream,
      sequenceToken="", # ignored by PutLogEvents
      logEvents=[{'timestamp': timestamp,'message': log_entry}])
```
Is there something wrong with my setup? Running python3.11. Any help would be greatly appreciated.
This is surely related to #10

**Comment by timstephenson20** [comment]
Seeing what seems to be much the same issue here. Running fine up until this morning, when we've presumably picked up an update containing https://github.com/labrixdigital/cloudwatch/issues/10


  File "/scripts/lib/helper_utils.py", line 18, in printLogInfo
    logger.info(logString)
  File "/usr/lib64/python3.9/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib64/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib64/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/usr/local/lib/python3.9/site-packages/cloudwatch/cloudwatch.py", line 103, in emit
    self._send(log_entry)
  File "/usr/local/lib/python3.9/site-packages/cloudwatch/cloudwatch.py", line 125, in _send
    self.send_log(timestamp, log_entry)
  File "/usr/local/lib/python3.9/site-packages/cloudwatch/cloudwatch.py", line 88, in send_log
    self.logs.put_log_events(logGroupName=self.log_group,
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 936, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 1007, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/usr/local/lib/python3.9/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter sequenceToken, value: 0, valid min length: 1

**Comment by ernestomi** [comment]
Thanks @StefanB7 @timstephenson20 , I have rolled back to 1.2.1, could you just confirm that you have stopped experiencing this issue?

**Comment by timstephenson20** [comment]
Thanks @ernestomi. The latest commit visible still seems to be 5606a896753cf2508d645d3c5fd15be0d59e876a from 18 hours ago? Can't see your mentioned version anywhere unfortunately. 

I can confirm however that reverting to the last commit from 1st Sept (9b2bb037640fc8e63ddbff14c360e90d82189162) "solves" the problem and everything seems to work exactly as it should! Hope that helps!

**Comment by ernestomi** [comment]
@timstephenson20 I thought you might have been using the pypi distribution (which is now back in line with ([9b2bb03](https://github.com/labrixdigital/cloudwatch/commit/9b2bb037640fc8e63ddbff14c360e90d82189162))

I have reverted the commit now on the repo. Thanks for your prompt response!

I will wait to hear from @StefanB7 to close the ticket and will address the bugs from #11 separately

**Comment by timstephenson20** [comment]
@ernestomi - Ahhh we were running with the distribution but were just grabbing the latest version, sorry for the confusion!!
Thanks for jumping on this, good luck with the bugs.

**Comment by StefanB7** [comment]
Can confirm its working now, thanks @ernestomi.

**Comment by ernestomi** [comment]
@StefanB7 @timstephenson20, could you let me know what version of boto3 you have?

```
pip3 show boto3
```

**Comment by StefanB7** [comment]
Version is 1.28.82
```console
Name: boto3
Version: 1.28.82
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email:
License: Apache License 2.0
```

**Comment by timstephenson20** [comment]
Looks like we're one point release ahead - 1.28.83
